### PR TITLE
feat: keyviz, lazyvim, and wezterm

### PR DESCRIPTION
**Pull request by syntaxboybe**

### CODE REVIEW

**Comment by syntaxboybe** [comment]
added new apps kindly check it @0PandaDEV

**Review by 0PandaDEV — CHANGES_REQUESTED** [review]
both wezterm and lazyvim need to be moved one up to be in the correct order

**Comment by syntaxboybe** [comment]
done

**Comment by syntaxboybe** [comment]
> both wezterm and lazyvim need to be moved one up to be in the correct order

done

**Review by 0PandaDEV — APPROVED** [review]
Perfect, thanks for your contribution

**Comment by syntaxboybe** [comment]
> Perfect, thanks for your contribution
your welcome

**Pull request merged**
