### PR TITLE
added steamunlocked

### PR DESCRIPTION
**Pull request by syntaxboybe**
+added:  Steam Unlocked allows you to download your favorite games pre-installed on steam without the cost.

### CODE REVIEW

**Comment by 0PandaDEV** [comment]
That's a good suggestion however I'm not sure if piracy is allowed in awesome list. On top of that it would not fit into awesome windows because it's a website.

**Comment by syntaxboybe** [comment]
> That's a good suggestion however I'm not sure if piracy is allowed on awesome list. On top of that it would not fit into awesome windows because it's a website.

for me its good coz not all can purchase games they want, so basically it depends on the persons perspective if piracy is bad or good 😄

**Comment by syntaxboybe** [comment]
and besides it safe i tried many times

**Comment by 0PandaDEV** [comment]
I know that its safe I also used it before but that still does not make it a windows (specific) app or tool

**Comment by 0PandaDEV** [comment]
Ok, I will add it, but it may change in the future.

**Pull request merged**
